baseURL = "https://manupascual.com/"
languageCode = "en-us"
title = "Manuel Pascual Luna"
theme = "cactus"

[params]
	colortheme = "classic"
	mainSection = "posts"
	rss = true

[[params.social]]
  name = "github"
  link = "https://github.com/grouchoboy"

[[params.social]]
	name = "twitter"
	link = "https://twitter.com/grouchoboy"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writing"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 4
